<?php

namespace common\Helper;


class EmailTemplate
{

    // ESS->LEAVE
    const EMAIL_TEMPLATE_LOGIN = "LOGI";
    const EMAIL_TEMPLATE_USER_REGISTERATION = "URNW";
    const EMAIL_TEMPLATE_SAFARI_OPERATOR_REGISTRATION = "STOR";
    const EMAIL_TEMPLATE_BIRDING_OPERATOR_REGISTRATION = "BTOR";
    const EMAIL_TEMPLATE_SAFARI_OPERATOR_FREE_QUOTE = "STOQ";
    const EMAIL_TEMPLATE_TOUR_OPERATOR_FREE_QUOTE_REQUEST = "TOQR";
    const EMAIL_TEMPLATE_USER_RECEIVED_REPLY_FREE_QUOTE = "URTQ";
    const EMAIL_TEMPLATE_ORGANIZE_NEW_SHARE_SAFARI = "ONSR";
    const EMAIL_TEMPLATE_SHARE_SAFARI_REQUEST_CONTACT = "SSRC";
    const EMAIL_TEMPLATE_FOLLOW_REQUEST = "SOFR";
    const EMAIL_TEMPLATE_UNFOLLOW_REQUEST = "SOUR";
    const EMAIL_TEMPLATE_REJECT_SHARE_SAFARI = "TRSS";
    const EMAIL_TEMPLATE_NEW_CONTACT_FORM_SUBMITTED = "NCFS";
    const EMAIL_TEMPLATE_OPERATOR_CREATED_NEW_PACKAGE = "OCNP";
    const EMAIL_TEMPLATE_NEW_SAFARI_CREATEDBY_USER = "NSCU";
    const EMAIL_TEMPLATE_OPERATOR_CREATED_NEW_FIXEDDEPARTURE = "OCNF";
    const EMAIL_TEMPLATE_NEW_SAFARI_OPERATOR_CREATED = "NSOC";
    const EMAIL_TEMPLATE_NEW_FLAGED_RAISEDBY_USER = "NFRU";
    const EMAIL_TEMPLATE_TO_HOST_JOIN_SAFARI = "THJS";
    const EMAIL_TEMPLATE_TO_HOST_ONCOMMENT_SAFARI = "THOS";
    const EMAIL_TEMPLATE_UPDATE_SAFARI_CREATEDBY_USER = "USCU";
    const EMAIL_TEMPLATE_COMMENT_REPLY_SAFARI = "REPL";
    const EMAIL_TEMPLATE_TO_MEMBER_ONCOMMENT_SAFARI = "TMOS";
    const EMAIL_TEMPLATE_UPDATE_FIXED_CREATEDBY_USER = "UFCU";
    const EMAIL_TEMPLATE_PACKAGE_COMMENT_BY_USER = "PCBU";
    const EMAIL_TEMPLATE_PACKAGE_REPLY_BY_USER = "PRBU";
    const EMAIL_TEMPLATE_REPLY_BY_USER_TO_COMMENTUSER = "RBUC";
    const EMAIL_TEMPLATE_REPLY_BY_ANYONE_USER = "RBAU";
    const EMAIL_TEMPLATE_FOLLOWER_BY_ANY_USER = "FBAU";
    const EMAIL_TEMPLATE_NEW_SAFARI_TO_FOLLOWER = "NSTF";
    const EMAIL_TEMPLATE_NEW_REVIEW_TO_OPERATOR = "NRTO";
    const EMAIL_TEMPLATE_QUOTATION_APPROVED_BY_ADMIN_FOR_USER = "QAAU";
    const EMAIL_TEMPLATE_QUOTATION_APPROVED_BY_ADMIN_FOR_OPERATOR = "QAAO";
    const EMAIL_TEMPLATE_QUOTATION_PAYMENT_RECEIVED_FOR_USER = "QPRU";
    const EMAIL_TEMPLATE_QUOTATION_PAYMENT_RECEIVED_FOR_PARTNER = "QPRP";
    const EMAIL_TEMPLATE_PAYMENT_RECEIVED_AGAINST_QUOTATION_FOR_USER = "PRQU";
    const EMAIL_TEMPLATE_PAYMENT_RECEIVED_AGAINST_QUOTATION_FOR_OPERATOR = "PRQO";


}
