<?php

namespace common\Helper;


class EmailTemplate
{

    // ESS->LEAVE
    const EMAIL_TEMPLATE_LOGIN = "LOGI";
    const EMAIL_TEMPLATE_USER_REGISTERATION = "URNW";
    const EMAIL_TEMPLATE_SAFARI_OPERATOR_REGISTRATION = "STOR";
    const EMAIL_TEMPLATE_BIRDING_OPERATOR_REGISTRATION = "BTOR";
    const EMAIL_TEMPLATE_SAFARI_OPERATOR_FREE_QUOTE = "STOQ";
}
